# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# The following line activates a set of stricter lints for Flutter apps
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Override specific rules if needed for this project
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    # Allow some flexibility for UI code
    prefer_const_constructors_in_immutables: false
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
