// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASrN_mr4GZSktCwQ24lfvrcCvpVA0Nv8U',
    appId: '1:752788778229:web:subtrackr',
    messagingSenderId: '752788778229',
    projectId: 'subtrackr-994ac',
    authDomain: 'subtrackr-994ac.firebaseapp.com',
    storageBucket: 'subtrackr-994ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASrN_mr4GZSktCwQ24lfvrcCvpVA0Nv8U',
    appId: '1:752788778229:android:com.kelvin.subtrackr',
    messagingSenderId: '752788778229',
    projectId: 'subtrackr-994ac',
    storageBucket: 'subtrackr-994ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrN_mr4GZSktCwQ24lfvrcCvpVA0Nv8U',
    appId: '1:752788778229:ios:212f453a3e8b10319ee9bc',
    messagingSenderId: '752788778229',
    projectId: 'subtrackr-994ac',
    storageBucket: 'subtrackr-994ac.firebasestorage.app',
    iosBundleId: 'com.kevs.subtrackr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrN_mr4GZSktCwQ24lfvrcCvpVA0Nv8U',
    appId: '1:752788778229:ios:212f453a3e8b10319ee9bc',
    messagingSenderId: '752788778229',
    projectId: 'subtrackr-994ac',
    storageBucket: 'subtrackr-994ac.firebasestorage.app',
    iosBundleId: 'com.kevs.subtrackr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASrN_mr4GZSktCwQ24lfvrcCvpVA0Nv8U',
    appId: '1:752788778229:web:subtrackr',
    messagingSenderId: '752788778229',
    projectId: 'subtrackr-994ac',
    authDomain: 'subtrackr-994ac.firebaseapp.com',
    storageBucket: 'subtrackr-994ac.firebasestorage.app',
  );
} 